name: Test & Deploy

on: [push, pull_request]
jobs:
  test-and-deploy:
    name: Test & Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up node and npm
      uses: actions/setup-node@v3
      with:
        version: 18

    - name: Install node dependencies
      run: npm install

    - name: Set up ruby and bundler
      uses: actions/setup-ruby@v1.1.3
      with:
        ruby-version: 2.6

    - name: Install ruby dependencies
      run: |
        gem install bundler -v 2.0.2
        bundle install

    - name: Set up python and pip
      uses: actions/setup-python@v4
      with:
        python-version: 3.7
        architecture: x64

    - name: Install AWS CLI
      run: pip install --user awscli

    - name: Build the blog
      run: npm run build-prod

    - name: Run tests
      run: |
        npm run markdown-lint
        npm run validate-front-matter
        npm run validate-images
        if ! bundle exec ./scripts/htmlproofer.rb;
        then
          echo "Failed HTML link validation."
          exit 1;
        else
          echo -e "\xE2\x9C\x94 No broken internal/external links!"
          exit 0;
        fi

    - name: Prep for Deploy
      run: npm run prep-for-deploy
